### ISSUE TITLE
[feat] - Make NavBar sticky

### ISSUE THREAD

**Issue by pritipsingh** [anomic30/Storz#101]
### Description

Having the navBar sticky, especially on the login and after the login page (upload part) will help users navigate easier and look cleaner. 
![Screenshot 2022-10-12 130942](https://user-images.githubusercontent.com/85965351/195281109-619540a4-eacc-441d-ab4d-c38574f5c0e4.png)

### Reproduction steps

```bash
1. Go to 'https://storz.pages.dev/'
2. Scroll down
4. See the navBar is gone and there is no option to sign in or upload.
```

### Browsers

Chrome

### OS

Windows

**Comment by JatinSingh08** [comment]
Hey @pritipsingh, Can you please assign this issue to me? I would love to work on this.

**Comment by pritipsingh** [comment]
@anomic30 can you check this one out

**Comment by shubhamjain1922** [comment]
Please assign this issue to me. I would like to work on this.

**Comment by Aditi-1709** [comment]
Please assign this to me, I can complete it in hardly 30 mins.

**Comment by anomic30** [comment]
Hi @Aditi-1709, @shubhamjain1922, @pritipsingh, currently our design team is not considering this sticky navbar. Therefore we are closing this issue as of now. Thank you.
