### ISSUE TITLE
🐛 [BUG] - deleting a file actually deletes all files

### ISSUE THREAD

**Issue by ThomasSed** [anomic30/Storz#105]
### Description

everything is in the title.
Must only delete the selected file

### Reproduction URL

https://github.com/ThomasSed/Storz

### Reproduction steps

```bash
1. Go to repository
2. Click on a file
3. Click on the trash button
4. accept
5. Go back to repository
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by anomic30** [comment]
Hi @ThomasSed,
This is happening because both files(having the same file names) have the same CID.
Currently, we are querying files for deletion based on their CID. If we can prevent this #104, we might be able to solve this too.

**Comment by ThomasSed** [comment]
a way to do this is by hashing the file using HMAC, and not simply sha-256.
storing the generated secret key on the db must do the trick here.
example (https://github.com/brix/crypto-js) : 

import hmacSHA512 from 'crypto-js/hmac-sha512';
import Base64 from 'crypto-js/enc-base64';

const  privateKey = uuid();
const hmac = Base64.stringify(hmacSHA512(file, privateKey));
