### ISSUE TITLE
🐛 [BUG] - Storz image from nav menu has a hover effect but it doesn't do anything

### ISSUE THREAD

**Issue by nujovich** [anomic30/Storz#20]
### Description

If the user is hovering over Storz image in the nav menu and clicks it, it doesn't do anything. Remove the hover or add a scroll up event

### Reproduction URL

https://storz.pages.dev/

### Reproduction steps

```bash
1. Go to https://storz.pages.dev/
2. Hover the Storz image in the nav menu on the top left
3. Click it
4. Nothing happens
```

### Browsers

Chrome

### OS

Windows

**Comment by anomic30** [comment]
Hi @nujovich, you can remove the hover effect.
