### ISSUE TITLE
🐛 [BUG] - Add margin for containers in Files section (width < 875px)

### ISSUE THREAD

**Issue by nujovich** [anomic30/Storz#21]
### Description

Currently, the application has set a width equal to 100%, even for mobile devices, which leads to content too attached to the margin of the page.

![image](https://user-images.githubusercontent.com/48018975/192792318-614ddf6b-3de7-4ae9-9bd0-208e9f5cf926.png)

### Reproduction URL

https://storz.pages.dev/app/myFiles/desc

### Reproduction steps

```bash
1. Go to 'https://storz.pages.dev' (width < 975px)
2. Click on 'Sign in'
3. Enter a valid email
4. Go to Files section
5. Click on file name
6. Containers have no margin set
```

### Screenshots

![image](https://user-images.githubusercontent.com/48018975/192792318-614ddf6b-3de7-4ae9-9bd0-208e9f5cf926.png)

### Browsers

Chrome

### OS

Windows

**Comment by julianfelipe98** [comment]
Hello, I would like to help you with this

**Comment by amreekminocha** [comment]
Hii is anyone working on this issue
If not you can assign it to me

**Comment by nujovich** [comment]
@julianfelipe98 @amreekminocha I am assigned to this

**Comment by AkashSharma001** [comment]
I have solved this bug.
Can I pull request?
@nujovich
