### ISSUE TITLE
🐛 [BUG] - Manage special characters in file names with Unicode

### ISSUE THREAD

**Issue by nujovich** [anomic30/Storz#22]
### Description

Currently, the application doesn't manage special characters like 'ó', 'á', 'é', 'í', 'ú' in an effective way.

![SpecialChars](https://user-images.githubusercontent.com/48018975/192792038-f9e65fc6-5132-4649-bebf-510151ab45ac.PNG)

### Reproduction URL

https://storz.pages.dev/app/myFiles/desc

### Reproduction steps

```bash
1. Go to 'https://storz.pages.dev' (width < 975px)
2. Click on 'Sign in'
3. Enter a valid email
4. Once logged in, upload a file with special chars in the name
5. See that once uploaded, the conversion is not being managed in an effective way
```

**Comment by julianfelipe98** [comment]
Hi, I would like to work on this issue

**Comment by nujovich** [comment]
@julianfelipe98 I've already assigned to this, sorry

**Comment by julianfelipe98** [comment]
:(
