### ISSUE TITLE
Rename .env.example file

### ISSUE THREAD

**Issue by Aniket1026** [anomic30/Storz#28]
In this issue I just want to include a small detail in the readme of the project
* Rename the env.example file
* Rename the file in both client and server folder 

I raised this issue as i faced an error which got resolved after renaming the files. So either we can rename the files or inform the contributor in readme about renaming the file.

**Comment by anomic30** [comment]
@Aniket1026 assigned.

**Comment by Aniket1026** [comment]
What should i do out of the two . Rename the file or Update the readme for contributor to rename ?

**Comment by anomic30** [comment]
Update the readme

**Comment by Gismo1337** [comment]
Oh. I dindt saw this issue. i added a pr https://github.com/anomic30/Storz/pull/42

sorry about that

**Comment by Aniket1026** [comment]
No worries @Gismo1337 😃 . It's fine
