### ISSUE TITLE
🐛 [BUG] - Bad responsiveness on file's tab.

### ISSUE THREAD

**Issue by Lofty-Brambles** [anomic30/Storz#30]
### Description

The files tab has a very squished look on a phone. Some margins and separations might be added to keep it clean.
Here's what it currently looks like.
![image](https://user-images.githubusercontent.com/100270817/193425800-7fdea0e1-928d-4c91-8557-3aca82d1d5ee.png)

### Reproduction URL

https://storz.pages.dev/app/myFiles

### Reproduction steps

```bash
1. Go to 'https://storz.pages.dev/app/myFiles'
2. Switch to a smaller screen in devtools
4. See the issue
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### OS

Windows, Linux

**Comment by Lofty-Brambles** [comment]
I'd like to work on this issue if possible.

**Comment by anomic30** [comment]
Hi @Lofty-Brambles, you can work on this issue.

**Comment by Lofty-Brambles** [comment]
![image](https://user-images.githubusercontent.com/100270817/193447011-03f051f9-c9e4-459e-8a1e-fba4c586e3a2.png)
Better now? @anomic30
