### ISSUE TITLE
🐛 Sign-in/log-in bug

### ISSUE THREAD

**Issue by chaaals** [anomic30/Storz#36]
### Description

Pressing enter on sign-in/log-in doesn't do anything. After looking briefly on the sign-in/login-in modal, I think the problem is that it's not using a form. I think this is bad for overall user experience.

### Reproduction URL

https://github.com/chaaals/Storz

### Reproduction steps

```bash
1. Go to sign-in/log-in page
2. Simply type in your information
3. Upon clicking enter~
4. It doesn't do any action
```

**Comment by chaaals** [comment]
If you think this is an issue that you need help with, I am happy to take over this issue @anomic30

**Comment by anomic30** [comment]
Hi @chaaals, you can work on this. Assigning it to you.
