### ISSUE TITLE
💡 Make a login button

### ISSUE THREAD

**Issue by Bibhavshah** [anomic30/Storz#38]
### Summary

Adding a login button instead of use now because it is more intuitive and the website becomes easy to use. Please assign me this issue. #hacktoberfest

### Basic Example

![Screenshot (1515)](https://user-images.githubusercontent.com/78656387/193442436-7a877658-7f4b-422c-864b-6b0f058dbc3f.png)

### Drawbacks

We have to remove the use Now button

**Comment by anomic30** [comment]
@Sneakad, What do you think?

**Comment by PiXeL99-eng** [comment]
Please assign me this issue, I am ready to work on it.

**Comment by anomic30** [comment]
@Bibhavshah & @PiXeL99-eng, it is not needed as of now.
