### ISSUE TITLE
Add a filtering feature

### ISSUE THREAD

**Issue by Sneakad** [anomic30/Storz#4]
Add a filtering feature to the My Files page.

For example :
- Filter by File types ( .pdf/.png/.jpeg etc )
- Filter by File status ( public/private )

**Comment by hxzqll** [comment]
Hi i'd like to take this issue

**Comment by anomic30** [comment]
Sure @hxzqll. Please wait for the UI.

**Comment by hxzqll** [comment]
@anomic30 sure, let me know when it's available.

**Comment by Sneakad** [comment]
Hello @hxzqll  here is the UI for the filtering feature
![filterin](https://user-images.githubusercontent.com/72182438/192149863-8b21f03d-c205-4a87-b10d-5b731e27a12d.png)

**Comment by ozair-dev** [comment]
Assign it to me.
