### ISSUE TITLE
💡 [REQUEST] - Add rate limiter to backend

### ISSUE THREAD

**Issue by developer-diganta** [anomic30/Storz#43]
### Summary

A rate limiter can be added to the backend to avoid slowloris attacks.

### Basic Example

This would avoid unnecessary open requests to server

### Drawbacks

It would limit requests per second from same ip (value can be changed though)

**Comment by developer-diganta** [comment]
If this seems legit can I work on it?

**Comment by anomic30** [comment]
Hi, you can work on this.
