### ISSUE TITLE
🐛 [BUG] - Bad responsiveness on the file information 

### ISSUE THREAD

**Issue by Joelute** [anomic30/Storz#47]
### Description

The files information page has a bad responsive design and on smaller screens/devices, the website will start to break. I believe that the root cause of this is that at smaller screens, the buttons will run out of room and start invading the padding and margin of its parent div. Allowing the button to wrap at a smaller size, it can provide it with more room and space to work with on a new line.

Here is what it looks like currently 

At 420px width
![image](https://user-images.githubusercontent.com/62449508/193475192-496c2178-eedd-474b-be21-e7e486e1033e.png)

At 320px width
![image](https://user-images.githubusercontent.com/62449508/193475245-6e9755b9-1ff4-4f63-ac25-576b36dd2d9b.png)

This is my proposed design:

![image](https://user-images.githubusercontent.com/62449508/193475318-77ccefdc-ff3e-4477-a04f-1ef8db02636a.png)

### Reproduction URL

https://storz.pages.dev/app/myFiles/desc

### Reproduction steps

```bash
1. Go to https://storz.pages.dev/app/home
2. Upload a file to the IPFS network
3. Go to https://storz.pages.dev/app/myFiles and open the file
4. Open devtool and adjust width to less than 420px
4. See the issue
```

### Screenshots

```bash
See in description
```

**Comment by Joelute** [comment]
I noticed that the issue has been resolved in a previous pull request, but I believe that this design makes better uses of the white space given and distributes it evenly. If this design is good, I would like to work on it.

**Comment by anomic30** [comment]
Hi @Joelute, currently it looks like this:

![image](https://user-images.githubusercontent.com/63467479/193633098-47b49408-3e91-4efc-a7bc-8c425a87b8e2.png)

Currently we don't have any requirement to change the design.
