### ISSUE TITLE
Add a dynamic 3D globe

### ISSUE THREAD

**Issue by Sneakad** [anomic30/Storz#5]
Add a dynamic 3D globe in the hero section of the landing page instead of the static globe png. (_try to use three.js_)

**Reference repo link**: https://github.com/nenadV91/Threejs-globe

**Color**: #00ffa8

**Reference image**:

![globe](https://user-images.githubusercontent.com/72182438/191467919-10a7f007-4c4b-48ae-845c-d27ac3350e27.png)

**Comment by rksingh2001** [comment]
Can I take up this issue? @Sneakad

**Comment by anomic30** [comment]
Hi @rksingh2001 , I am assigning this issue to you.

**Comment by rksingh2001** [comment]
@anomic30 While trying to generate new key, infura.io is asking for a credit card? I don't have one what should I do?

**Comment by anomic30** [comment]
Hi, @rksingh2001 
Join our [Discord](https://discord.gg/WPBFRDj5) server and DM me to get the keys.

**Comment by Anuran12** [comment]
hi @anomic30 can you assign it to me ?

**Comment by rksingh2001** [comment]
@Anuran12 I am working on this issue, currently.

**Comment by rksingh2001** [comment]
@Sneakad Do we want to show the country names as well? Because I feel that will look a little too clunky?

**Comment by Sneakad** [comment]
@rksingh2001 You can remove the country names and implement it

**Comment by Anuran12** [comment]
> @Anuran12 I am working on this issue, currently.

are you still working on this ?
