### ISSUE TITLE
adding a back to top button at the bottom of the webpage

### ISSUE THREAD

**Issue by dreymotoh** [anomic30/Storz#51]
### Summary

having a back to top function button at the bottom of the webpage to allow users to get back to top quickly

### Basic Example

button that will return to top when clicked

### Drawbacks

where to place it

**Comment by anomic30** [comment]
Hi @dreymotoh, someone is already working on this [#37]

**Comment by dreymotoh** [comment]
ok great :) !

**Comment by dreymotoh** [comment]
by the way !! the webpage looks great

**Comment by anomic30** [comment]
Thank you @dreymotoh 😊
