### ISSUE TITLE
[ENHANCEMENT]- Enhance navigation on Files section when file name is too big

### ISSUE THREAD

**Issue by nujovich** [anomic30/Storz#56]
### Description

Currently the Files section actives the horizontal scrolling when a file name is too big

![image](https://user-images.githubusercontent.com/48018975/193726016-74c69263-7c1f-4f13-8045-83a1b36d005f.png)

### Reproduction URL

https://storz.pages.dev/app/myFiles

### Reproduction steps

```bash
1. Go to the Storz app https://storz.pages.dev/
2. Login
3. Add a new file with a large name
4. See behavior
```

### Screenshots

```bash
![image](https://user-images.githubusercontent.com/48018975/193726016-74c69263-7c1f-4f13-8045-83a1b36d005f.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by nujovich** [comment]
If applicable assign it to me

**Comment by anomic30** [comment]
Hi @nujovich, great job finding this bug!
Do you want to truncate the filename or wrap the remaining word in the next line?

**Comment by nujovich** [comment]
Great! Np

**Comment by nujovich** [comment]
@anomic30 I think truncating the filename is a better choice than wrapping it, this is causing issues here also:

![image](https://user-images.githubusercontent.com/48018975/193908311-cf73fc68-9d44-473e-89b2-f4c9b8d850d3.png)

What's the fixed max length you suggest need to set up for a filename?
