### ISSUE TITLE
[Enhancement] - Console Logging

### ISSUE THREAD

**Issue by ezehlivinus** [anomic30/Storz#61]
Setup a basic console/terminal messages/logs to show when HTTP requests are made and when the app is running. This way it helps with debugging especially during development.

When a request is sent: The request methods, endpoint and status code would be logged to the console. The standard logger would be used instead of console.log().

**Comment by ezehlivinus** [comment]
@anomic30 please can you look at this and assign it to me?

**Comment by anomic30** [comment]
Hi @ezehlivinus, assigning it to you.
