### ISSUE TITLE
💡 [REQUEST] - About page for app

### ISSUE THREAD

**Issue by nishtha53** [anomic30/Storz#73]
### Summary

Can we add about page for this I need to discuss content for about page

### Basic Example

we can add about app what does app do team photos in about

### Drawbacks

Need for content help

**Comment by adetyaz** [comment]
Hello, is there a design available for the about page and can I build it?
🙂

**Comment by nishtha53** [comment]
Okay sure @anomic30

**Comment by adetyaz** [comment]
Okay no problem
