### ISSUE TITLE
Lint: Add pre-commit hook

### ISSUE THREAD

**Issue by ezehlivinus** [anomic30/Storz#75]
The project needs a pre-hook commit that will run to lint and format the change to the project before it gets committed to git.

Given that linting and formatting have been configured for the project, setting up a `pre-commit hook` will help lint and format changes on committing.

**Comment by ezehlivinus** [comment]
@anomic30  Please assign this to me and update the necessary labels.

There is a problem with this:
1. husky or [lint-style](https://github.com/okonet/lint-staged) require that .git/, package.json are all same directory
2. Because the `Storz/ `folder has the `.git/ `folder and no package.json file, this may be difficult to work

git commit is best executed where .git/ exists, while npm/yarn is also best executed where package.json exist.

What do you think?

**Comment by anomic30** [comment]
@ezehlivinus, So we need to separate our client and server into two different repos. Currently, we won't be able to do this can consider it later for sure. Meanwhile, I am closing this issue.

**Comment by ezehlivinus** [comment]
> @ezehlivinus, So we need to separate our client and server into two different repos. Currently, we won't be able to do this, can consider it later for sure. Meanwhile, I am closing this issue.

Okay fine...
