### ISSUE TITLE
🐛 [BUG] - File not uploading

### ISSUE THREAD

**Issue by detronetdip** [anomic30/Storz#8]
### Description

Each and every time I am uploading a file it is showing me the below image. what that `x` sign mean and there were no error message as well.

### Reproduction URL

no

### Reproduction steps

```bash
1. Go to the website
2. Click on upload files
4. See error
```

### Screenshots

![Screenshot from 2022-09-24 21-41-30](https://user-images.githubusercontent.com/64276906/192108158-cda718dd-fba1-48e2-831e-fc34e474ea8b.png)

### Browsers

Chrome

### OS

Linux

**Comment by detronetdip** [comment]
Just checked my console output in the browser and found this.

![Screenshot from 2022-09-24 21-52-02](https://user-images.githubusercontent.com/64276906/192108511-1a32bf22-910a-4ea2-ab64-a0fa3b105d12.png)
  
It is saying that `Magic Admin SDK Error: [ERROR_MALFORMED_TOKEN] The DID token is malformed or failed to parse.` seams like Decentralized ID tokens is malformed.

**Comment by anomic30** [comment]
Try clearing the cookies as well as local storage and try again
